language: python
python:
  - "3.6"

sudo: false
cache: pip

install: "pip install sphinx sphinx_rtd_theme"
script: docs/build.sh

deploy:
  provider: script
  script: docs/deploy.sh
  on:
    branch: doc_generation