language: python
python:
  - "3.6"

sudo: false
cache: pip

install:
  - "pip install sphinx sphinx_rtd_theme recommonmark"
  - pip install -r requirements.txt
  - pip install pytest

script:
  - docs/build.sh
  - pytest

deploy:
  skip_cleanup: true
  provider: script
  script: bash docs/deploy.sh
  on:
    branch: master