language: python
python:
  - "3.6"

sudo: false
cache: pip

install:
  - "pip install sphinx sphinx_rtd_theme"
  - pip install -r requirements.txt
script: docs/build.sh

deploy:
  skip_cleanup: true
  provider: script
  script: bash docs/deploy.sh
  on:
    branch: doc_generation